from flask import Flask, render_template, request, send_from_directory
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from werkzeug.utils import secure_filename

import hashlib
import json
import os
import uuid
from datetime import datetime
import textwrap

from flask_cors import CORS

app = Flask(__name__)
CORS(app)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

REPORT_FOLDER = os.path.join(BASE_DIR, "reports")
UPLOAD_FOLDER = os.path.join(BASE_DIR, "uploads")
DATA_FOLDER = os.path.join(BASE_DIR, "data")

os.makedirs(REPORT_FOLDER, exist_ok=True)
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(DATA_FOLDER, exist_ok=True)

HASH_FILE = os.path.join(DATA_FOLDER, "report_hashes.json")
AUDIT_FILE = os.path.join(DATA_FOLDER, "audit_log.json")

app.config["MAX_CONTENT_LENGTH"] = 5 * 1024 * 1024

ALLOWED_EXTENSIONS = {"pdf", "txt"}


def calculate_sha256(file_path):
    sha256 = hashlib.sha256()

    with open(file_path, "rb") as file:
        while True:
            chunk = file.read(4096)

            if not chunk:
                break

            sha256.update(chunk)

    return sha256.hexdigest()


def read_json(file_path):
    if not os.path.exists(file_path):
        return []

    try:
        with open(file_path, "r", encoding="utf-8") as file:
            data = json.load(file)
            return data if isinstance(data, list) else []
    except (OSError, json.JSONDecodeError):
        return []


def write_json(file_path, data):
    with open(file_path, "w", encoding="utf-8") as file:
        json.dump(data, file, indent=4)


def add_audit_log(action, filename, status):
    logs = read_json(AUDIT_FILE)

    logs.append({
        "timestamp": datetime.now().isoformat(),
        "action": action,
        "filename": filename,
        "status": status
    })

    write_json(AUDIT_FILE, logs)


def create_text_report(report_id, case_id, title, analyst, summary, findings):
    filename = f"{report_id}.txt"
    path = os.path.join(REPORT_FOLDER, filename)

    report = f"""AI-POWERED CRIMINAL NETWORK ANALYSIS SYSTEM
CASE ANALYSIS REPORT

Report ID: {report_id}
Case ID: {case_id}
Case Title: {title}
Generated By: {analyst}
Generated At: {datetime.now().strftime("%d-%m-%Y %H:%M:%S")}

--------------------------------------------------

CASE SUMMARY

{summary}

--------------------------------------------------

ANALYSIS FINDINGS

{findings}

--------------------------------------------------

SYSTEM NOTICE

This report was generated by the Criminal Network Analysis System.
Report integrity can be verified using the associated SHA-256 seal.
"""

    with open(path, "w", encoding="utf-8") as file:
        file.write(report)

    return filename, path


def create_pdf_report(report_id, case_id, title, analyst, summary, findings):
    filename = f"{report_id}.pdf"
    path = os.path.join(REPORT_FOLDER, filename)

    pdf = canvas.Canvas(path, pagesize=A4)
    width, height = A4
    y = height - 60

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(50, y, "AI Criminal Network Analysis")
    y -= 25

    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(50, y, "CASE ANALYSIS REPORT")
    y -= 40

    pdf.setFont("Helvetica", 10)
    information = [
        f"Report ID: {report_id}",
        f"Case ID: {case_id}",
        f"Case Title: {title}",
        f"Analyst: {analyst}",
        f"Generated: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
        "",
        "CASE SUMMARY",
        summary,
        "",
        "ANALYSIS FINDINGS",
        findings
    ]

    for item in information:
        wrapped_lines = textwrap.wrap(item, width=85) or [""]

        for line in wrapped_lines:
            if y < 60:
                pdf.showPage()
                y = height - 60
                pdf.setFont("Helvetica", 10)

            pdf.drawString(50, y, line)
            y -= 16

    pdf.save()
    return filename, path


def save_report_hash(filename, file_hash):
    hashes = read_json(HASH_FILE)

    hashes.append({
        "filename": filename,
        "sha256": file_hash,
        "created_at": datetime.now().isoformat()
    })

    write_json(HASH_FILE, hashes)


def find_original_hash(filename):
    hashes = read_json(HASH_FILE)

    for report in reversed(hashes):
        if report.get("filename") == filename:
            return report.get("sha256")

    return None


def allowed_file(filename):
    return (
        "." in filename
        and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS
    )


def validate_uploaded_file(file):
    if not file or not file.filename:
        return False, "Please select a report before verification."

    if not allowed_file(file.filename):
        return False, "Unsupported file format. Upload a PDF or TXT report."

    extension = file.filename.rsplit(".", 1)[1].lower()
    first_bytes = file.stream.read(5)
    file.stream.seek(0)

    if extension == "pdf" and not first_bytes.startswith(b"%PDF-"):
        return False, "Invalid PDF file."

    return True, "File accepted."


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/generate", methods=["GET", "POST"])
def generate_report():
    if request.method == "GET":
        return render_template("index.html")

    case_id = request.form.get("case_id", "").strip()
    title = request.form.get("title", "").strip()
    analyst = request.form.get("analyst", "").strip()
    summary = request.form.get("summary", "").strip()
    findings = request.form.get("findings", "").strip()

    if not all([case_id, title, analyst, summary, findings]):
        return render_template(
            "index.html",
            generation_message="Please complete every case report field.",
            generation_status="error"
        ), 400

    report_id = "REPORT-" + uuid.uuid4().hex[:8].upper()

    txt_filename, txt_path = create_text_report(
        report_id, case_id, title, analyst, summary, findings
    )
    pdf_filename, pdf_path = create_pdf_report(
        report_id, case_id, title, analyst, summary, findings
    )

    txt_hash = calculate_sha256(txt_path)
    pdf_hash = calculate_sha256(pdf_path)
    save_report_hash(txt_filename, txt_hash)
    save_report_hash(pdf_filename, pdf_hash)
    add_audit_log("REPORT_GENERATED", pdf_filename, "SUCCESS")

    return render_template(
        "index.html",
        generated=True,
        report_id=report_id,
        pdf_filename=pdf_filename,
        txt_filename=txt_filename,
        pdf_hash=pdf_hash,
        txt_hash=txt_hash
    )


@app.route("/download/<filename>")
def download_report(filename):
    return send_from_directory(REPORT_FOLDER, filename, as_attachment=True)


@app.route("/verify", methods=["GET", "POST"])
def verify_report():
    if request.method == "GET":
        return render_template("index.html")

    file = request.files.get("report")
    valid, message = validate_uploaded_file(file)

    if not valid:
        return render_template(
            "index.html",
            verification_message=message,
            verification_status="error"
        ), 400

    filename = secure_filename(file.filename)
    upload_path = os.path.join(UPLOAD_FOLDER, filename)
    file.save(upload_path)
    uploaded_hash = calculate_sha256(upload_path)
    original_hash = find_original_hash(filename)

    if original_hash is None:
        add_audit_log("REPORT_VERIFICATION", filename, "UNKNOWN_REPORT")
        message = "Report not found in the system registry."
        status = "error"
    elif uploaded_hash == original_hash:
        add_audit_log("REPORT_VERIFICATION", filename, "VERIFIED")
        message = "Report Verified - Integrity Confirmed."
        status = "success"
    else:
        add_audit_log("REPORT_VERIFICATION", filename, "MODIFIED")
        message = "Verification Failed - Report integrity mismatch detected."
        status = "error"

    return render_template(
        "index.html",
        verification_message=message,
        verification_status=status,
        uploaded_hash=uploaded_hash
    )


@app.errorhandler(413)
def request_entity_too_large(error):
    return render_template(
        "index.html",
        verification_message="Upload failed. Maximum file size is 5 MB.",
        verification_status="error"
    ), 413

from flask import jsonify


@app.route("/api/generate", methods=["POST"])
def api_generate_report():
    data = request.get_json()

    case_id = (data.get("case_id") or "").strip()
    title = (data.get("title") or "").strip()
    analyst = (data.get("analyst") or "").strip()
    summary = (data.get("summary") or "").strip()
    findings = (data.get("findings") or "").strip()

    if not all([case_id, title, analyst, summary, findings]):
        return jsonify({"error": "Please complete every case report field."}), 400

    report_id = "REPORT-" + uuid.uuid4().hex[:8].upper()

    txt_filename, txt_path = create_text_report(
        report_id, case_id, title, analyst, summary, findings
    )
    pdf_filename, pdf_path = create_pdf_report(
        report_id, case_id, title, analyst, summary, findings
    )

    txt_hash = calculate_sha256(txt_path)
    pdf_hash = calculate_sha256(pdf_path)
    save_report_hash(txt_filename, txt_hash)
    save_report_hash(pdf_filename, pdf_hash)
    add_audit_log("REPORT_GENERATED", pdf_filename, "SUCCESS")

    return jsonify({
        "report_id": report_id,
        "case_id": case_id,
        "title": title,
        "analyst": analyst,
        "pdf_filename": pdf_filename,
        "txt_filename": txt_filename,
        "pdf_hash": pdf_hash,
        "txt_hash": txt_hash,
    })


@app.route("/api/reports", methods=["GET"])
def api_list_reports():
    hashes = read_json(HASH_FILE)

    reports = {}
    for entry in hashes:
        filename = entry["filename"]
        report_id = filename.rsplit(".", 1)[0]
        ext = filename.rsplit(".", 1)[1]

        if report_id not in reports:
            reports[report_id] = {"report_id": report_id, "created_at": entry["created_at"]}

        reports[report_id][f"{ext}_filename"] = filename
        reports[report_id][f"{ext}_hash"] = entry["sha256"]

    return jsonify(list(reports.values())[::-1])


@app.route("/api/verify", methods=["POST"])
def api_verify_report():
    file = request.files.get("report")
    valid, message = validate_uploaded_file(file)

    if not valid:
        return jsonify({"status": "error", "message": message}), 400

    filename = secure_filename(file.filename)
    upload_path = os.path.join(UPLOAD_FOLDER, filename)
    file.save(upload_path)
    uploaded_hash = calculate_sha256(upload_path)
    original_hash = find_original_hash(filename)

    if original_hash is None:
        add_audit_log("REPORT_VERIFICATION", filename, "UNKNOWN_REPORT")
        return jsonify({"status": "error", "message": "Report not found in the system registry."})
    elif uploaded_hash == original_hash:
        add_audit_log("REPORT_VERIFICATION", filename, "VERIFIED")
        return jsonify({"status": "success", "message": "Report Verified - Integrity Confirmed.", "hash": uploaded_hash})
    else:
        add_audit_log("REPORT_VERIFICATION", filename, "MODIFIED")
        return jsonify({"status": "error", "message": "Verification Failed - Report integrity mismatch detected.", "hash": uploaded_hash})

if __name__ == "__main__":
    app.run(debug=True)